import type { Recipe, Product } from '@/types';

export const recipes: Recipe[] = [
  {
    id: 'r1',
    slug: 'brown-butter-chocolate-chip-cookies',
    title: 'Brown Butter Chocolate Chip Cookies',
    category: 'Cookies',
    description: 'Nutty, deeply caramelized brown butter meets pools of dark chocolate in our signature cookie. Crisp at the edges, molten in the middle.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=1600&q=80&auto=format&fit=crop',
    prepTime: '20 min',
    cookTime: '12 min',
    servings: '18 cookies',
    difficulty: 'Easy',
    ingredients: [
      '1 cup unsalted butter',
      '1 cup light brown sugar, packed',
      '½ cup granulated sugar',
      '2 large eggs, room temperature',
      '2 tsp pure vanilla extract',
      '2¼ cups all-purpose flour',
      '1 tsp baking soda',
      '1 tsp flaky sea salt',
      '2 cups dark chocolate, roughly chopped',
    ],
    steps: [
      'Brown the butter in a light-colored saucepan over medium heat until deeply golden and fragrant, about 6–8 minutes. Pour into a heatproof bowl and let cool until just warm.',
      'Whisk the browned butter with both sugars until smooth and glossy. Add eggs one at a time, then vanilla.',
      'In a separate bowl, whisk flour, baking soda, and sea salt. Fold dry into wet until just combined, then fold in the chopped chocolate.',
      'Chill the dough for at least 30 minutes (overnight is better). Preheat oven to 375°F (190°C).',
      'Scoop generous portions onto a lined sheet, leaving space between. Bake 11–13 minutes until edges are set but centers look slightly underdone.',
      'Finish with flaky sea salt and let rest on the tray for 10 minutes before transferring.',
    ],
    featured: true,
  },
  {
    id: 'r2',
    slug: 'olive-oil-citrus-cake',
    title: 'Olive Oil & Citrus Cake',
    category: 'Cakes',
    description: 'A tender, fragrant cake made with fruity olive oil, fresh orange zest, and a whisper of cardamom. Effortless and unforgettable.',
    image: 'https://images.unsplash.com/photo-1505976378723-9726b54e9bb9?w=1600&q=80&auto=format&fit=crop',
    prepTime: '15 min',
    cookTime: '45 min',
    servings: '8 slices',
    difficulty: 'Easy',
    ingredients: [
      '1 cup extra virgin olive oil',
      '1¼ cups granulated sugar',
      '3 large eggs',
      'Zest of 2 oranges',
      '¾ cup whole milk',
      '2 cups all-purpose flour',
      '2 tsp baking powder',
      '½ tsp ground cardamom',
      '¼ tsp fine sea salt',
    ],
    steps: [
      'Preheat oven to 350°F (175°C). Grease and line a 9-inch round pan.',
      'Whisk olive oil and sugar until pale. Add eggs one at a time, then zest and milk.',
      'Sift in flour, baking powder, cardamom, and salt. Whisk just until smooth.',
      'Pour into the pan and bake 40–50 minutes until a tester comes out clean.',
      'Cool, then dust with powdered sugar and finish with extra zest.',
    ],
  },
  {
    id: 'r3',
    slug: 'sourdough-focaccia',
    title: 'Slow-Fermented Sourdough Focaccia',
    category: 'Bread',
    description: 'Pillowy, dimpled, and drenched in golden olive oil. A 24-hour ferment yields the kind of focaccia that ruins all others.',
    image: 'https://images.unsplash.com/photo-1568471173242-461f0a730452?w=1600&q=80&auto=format&fit=crop',
    prepTime: '30 min',
    cookTime: '25 min',
    servings: '12 squares',
    difficulty: 'Intermediate',
    ingredients: [
      '500g bread flour',
      '400g cool water',
      '100g active sourdough starter',
      '10g fine sea salt',
      '60ml extra virgin olive oil, plus more',
      'Flaky salt and fresh rosemary',
    ],
    steps: [
      'Mix flour, water, and starter until shaggy. Rest 30 minutes (autolyse).',
      'Add salt and a splash of water. Perform 4 sets of stretch-and-folds, 30 minutes apart.',
      'Cover and refrigerate overnight (12–18 hours).',
      'Pour into an oiled pan, dimple gently, and let rise 2–3 hours until pillowy.',
      'Drizzle with olive oil, scatter rosemary and salt. Bake at 450°F (230°C) for 22–25 minutes.',
    ],
  },
  {
    id: 'r4',
    slug: 'salted-honey-pie',
    title: 'Salted Honey Pie',
    category: 'Pies',
    description: 'A custardy, caramel-edged pie sweetened with raw honey and finished with flaky salt. Quietly extraordinary.',
    image: 'https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=1600&q=80&auto=format&fit=crop',
    prepTime: '25 min',
    cookTime: '55 min',
    servings: '8 slices',
    difficulty: 'Intermediate',
    ingredients: [
      '1 single-crust pie dough, blind-baked',
      '½ cup unsalted butter, melted',
      '¾ cup raw honey',
      '½ cup granulated sugar',
      '3 large eggs + 1 yolk',
      '¼ cup heavy cream',
      '1 tbsp white vinegar',
      '1 tsp vanilla',
      'Flaky sea salt',
    ],
    steps: [
      'Preheat oven to 350°F (175°C).',
      'Whisk butter, honey, and sugar. Add eggs, yolk, cream, vinegar, and vanilla.',
      'Pour into the blind-baked crust and bake 45–55 minutes until just set with a slight wobble.',
      'Cool completely, then finish with flaky salt before slicing.',
    ],
  },
  {
    id: 'r5',
    slug: 'morning-buns',
    title: 'Cardamom Morning Buns',
    category: 'Pastry',
    description: 'Flaky, laminated dough rolled with cardamom sugar and baked until shatteringly golden. A weekend ritual.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1600&q=80&auto=format&fit=crop',
    prepTime: '2 hours',
    cookTime: '25 min',
    servings: '12 buns',
    difficulty: 'Advanced',
    ingredients: [
      '1 batch croissant dough (laminated)',
      '½ cup granulated sugar',
      '2 tsp freshly ground cardamom',
      '1 tsp cinnamon',
      'Zest of 1 orange',
      'Pearl sugar, to finish',
    ],
    steps: [
      'Roll laminated dough to a 12x18 rectangle.',
      'Mix sugar, spices, and zest; sprinkle generously over the dough.',
      'Roll tightly from the long side, slice into 12 pieces, and place in a buttered muffin tin.',
      'Proof until puffy, about 90 minutes.',
      'Bake at 400°F (200°C) for 22–25 minutes until deeply golden. Finish with pearl sugar.',
    ],
  },
  {
    id: 'r6',
    slug: 'tahini-banana-bread',
    title: 'Tahini Banana Bread',
    category: 'Quick Bread',
    description: 'A grown-up banana bread with toasted sesame, dark muscovado, and a swirl of nutty tahini through every slice.',
    image: 'https://images.unsplash.com/photo-1606101205452-65898ed47e6b?w=1600&q=80&auto=format&fit=crop',
    prepTime: '15 min',
    cookTime: '55 min',
    servings: '1 loaf',
    difficulty: 'Easy',
    ingredients: [
      '3 very ripe bananas',
      '½ cup tahini',
      '½ cup melted butter',
      '¾ cup muscovado sugar',
      '2 eggs',
      '1¾ cups flour',
      '1 tsp baking soda',
      '½ tsp salt',
      'Sesame seeds, to top',
    ],
    steps: [
      'Preheat oven to 350°F. Line a loaf pan.',
      'Mash bananas, whisk in tahini, butter, sugar, and eggs.',
      'Fold in flour, soda, and salt until just combined.',
      'Pour into the pan, swirl with extra tahini, top with sesame seeds.',
      'Bake 50–60 minutes until set. Cool before slicing.',
    ],
  },
  {
    id: 'r7',
    slug: 'pistachio-financiers',
    title: 'Pistachio Financiers',
    category: 'Pastry',
    description: 'Tiny brown-butter cakes with a crisp shell and tender, almond-pistachio crumb. The perfect afternoon companion.',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=1600&q=80&auto=format&fit=crop',
    prepTime: '20 min',
    cookTime: '15 min',
    servings: '16 financiers',
    difficulty: 'Intermediate',
    ingredients: [
      '½ cup brown butter',
      '¾ cup powdered sugar',
      '½ cup almond flour',
      '¼ cup pistachio flour',
      '⅓ cup all-purpose flour',
      '4 egg whites',
      'Pinch of salt',
      'Chopped pistachios, to top',
    ],
    steps: [
      'Whisk dry ingredients together.',
      'Add egg whites and whisk until smooth. Stream in warm brown butter.',
      'Rest the batter 30 minutes. Preheat oven to 400°F.',
      'Pipe into buttered molds, top with pistachios, and bake 12–15 minutes.',
    ],
  },
  {
    id: 'r8',
    slug: 'lemon-tart',
    title: 'Classic Lemon Tart',
    category: 'Pies',
    description: 'A bracingly bright lemon curd in a crisp, buttery shell. Restraint is the recipe.',
    image: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=1600&q=80&auto=format&fit=crop',
    prepTime: '30 min',
    cookTime: '35 min',
    servings: '8 slices',
    difficulty: 'Intermediate',
    ingredients: [
      '1 sweet tart shell, blind-baked',
      '¾ cup fresh lemon juice',
      'Zest of 3 lemons',
      '1 cup sugar',
      '4 eggs + 2 yolks',
      '¾ cup unsalted butter, cubed',
    ],
    steps: [
      'Combine juice, zest, sugar, and eggs over a double boiler. Whisk until thick.',
      'Off heat, whisk in butter a few cubes at a time until silky.',
      'Strain into the tart shell. Bake at 325°F for 10 minutes to set.',
      'Chill thoroughly before slicing.',
    ],
  },
];

export const products: Product[] = [
  {
    id: 'p1',
    slug: 'signature-linen-apron',
    name: 'Signature Linen Apron',
    price: 68,
    category: 'Aprons',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1556909211-d5b07a5f8f72?w=1200&q=80&auto=format&fit=crop',
    ],
    description: 'Heavyweight European linen, garment-washed for that perfectly lived-in feel. Adjustable straps, two hand-stitched pockets, and the kind of drape that gets better with every wash.',
    details: [
      '100% European linen, 230 gsm',
      'Adjustable cross-back straps',
      'Two roomy pockets, double-stitched',
      'Machine wash cold, tumble dry low',
      'Ethically made in Portugal',
    ],
    isNew: true,
  },
  {
    id: 'p2',
    slug: 'walnut-rolling-pin',
    name: 'French Walnut Rolling Pin',
    price: 54,
    category: 'Tools',
    image: 'https://images.unsplash.com/photo-1612883417379-9569cb4ada06?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1612883417379-9569cb4ada06?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=1200&q=80&auto=format&fit=crop',
    ],
    description: 'Hand-turned from a single piece of French walnut. The weight does the work — no handles, no fuss, just beautiful dough.',
    details: [
      '19 inches, solid French walnut',
      'Tapered French-style profile',
      'Hand-rubbed beeswax finish',
      'Hand wash only',
    ],
    isNew: true,
  },
  {
    id: 'p3',
    slug: 'ceramic-mixing-bowls',
    name: 'Stoneware Mixing Bowl Set',
    price: 124,
    category: 'Bowls',
    image: 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=1200&q=80&auto=format&fit=crop',
    ],
    description: 'A nesting trio of hand-thrown stoneware in our signature cream glaze. Heavy enough to stay put, beautiful enough to live on the counter.',
    details: [
      'Set of 3: 1qt, 2qt, 4qt',
      'Hand-thrown stoneware',
      'Lead-free cream glaze',
      'Dishwasher and oven safe',
    ],
    isNew: true,
  },
  {
    id: 'p4',
    slug: 'brass-measuring-spoons',
    name: 'Brass Measuring Spoons',
    price: 38,
    category: 'Tools',
    image: 'https://images.unsplash.com/photo-1620207418302-439b387441b0?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1620207418302-439b387441b0?w=1200&q=80&auto=format&fit=crop',
    ],
    description: 'Solid brass measuring spoons that develop a beautiful patina with use. A small upgrade that feels like a daily indulgence.',
    details: [
      'Set of 4: ¼ tsp, ½ tsp, 1 tsp, 1 tbsp',
      'Solid unlacquered brass',
      'Leather tie included',
      'Hand wash, dry immediately',
    ],
  },
  {
    id: 'p5',
    slug: 'pastry-brush',
    name: 'Natural Bristle Pastry Brush',
    price: 24,
    category: 'Tools',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1200&q=80&auto=format&fit=crop',
    ],
    description: 'Soft boar bristles set in a turned beechwood handle. For glazing, washing, and finishing with intention.',
    details: [
      '8-inch beechwood handle',
      'Natural boar bristles',
      'Hand wash, air dry',
    ],
  },
  {
    id: 'p6',
    slug: 'linen-tea-towels',
    name: 'Linen Tea Towel Set',
    price: 42,
    category: 'Linens',
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=1200&q=80&auto=format&fit=crop',
    ],
    description: 'A set of three stonewashed linen towels in cream, oat, and terracotta. Absorbent, beautiful, endlessly useful.',
    details: [
      'Set of 3 towels, 20" x 28"',
      '100% stonewashed linen',
      'Machine wash cold',
    ],
  },
  {
    id: 'p7',
    slug: 'recipe-journal',
    name: 'The Alchenny Recipe Journal',
    price: 32,
    category: 'Paper',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=1200&q=80&auto=format&fit=crop',
    ],
    description: 'A linen-bound journal designed for the way bakers actually work — with space for notes, ratios, and the inevitable scribbled adjustments.',
    details: [
      '200 pages, FSC-certified paper',
      'Linen hardcover',
      'Lay-flat binding',
      'Made in Italy',
    ],
  },
  {
    id: 'p8',
    slug: 'oven-mitts',
    name: 'Quilted Linen Oven Mitts',
    price: 48,
    category: 'Linens',
    image: 'https://images.unsplash.com/photo-1631799884906-a9554dee78a5?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1631799884906-a9554dee78a5?w=1200&q=80&auto=format&fit=crop',
    ],
    description: 'Triple-layered, hand-quilted linen oven mitts. The kind of thing you want hanging on the hook, in view.',
    details: [
      'Set of 2',
      'Heat-resistant to 500°F',
      'Hand-quilted in Portugal',
    ],
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return recipes.find((r) => r.slug === slug);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
